---
abstract: 'Perl implementation of GNTP Protocol (Client Part)'
author:
  - 'Yasuhiro Matsumoto <mattn.jp@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.51, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Growl-GNTP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  Growl::GNTP:
    file: lib/Growl/GNTP.pm
    version: 0.19
requires:
  Crypt::CBC: 2.29
  Data::UUID: 0.149
  Digest::MD5: 2.36
  Digest::SHA: 5.45
  Filter::Util::Call: 0
resources:
  bugtracker: https://github.com/mattn/p5-Growl-GNTP/issues
  homepage: https://github.com/mattn/p5-Growl-GNTP
  repository: git://github.com/mattn/p5-Growl-GNTP
version: 0.19
x_contributors:
  - 'unknown <Administrator@.(none)>'
  - 'Yuki Ibe <yibe@yibe.org>'
  - 'mattn <mattn@poo.(none)>'
  - 'Marc Thielemann <marc.thielemann@biama.de>'
  - 'sugyan <sugi1982@gmail.com>'
  - 'Henrik Brix Andersen <henrik@brixandersen.dk>'
  - 'John Morrissey <jwm@horde.net>'
